#pragma once

#define MAIN_Version "83e3797"
#define KNX_Version "2.3.1+7124a64"
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_Common_Version "1.8.1+f6dbb3c"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 8
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 24
#define MODULE_LogicModule_Version "4.3.0+8c0d835"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 3
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 67
#define MODULE_FunctionBlocks_Version "0.10.0+142bd5b"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 10
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 10
#define MODULE_BinaryInput_Version "0.3.1+19e648c"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 3
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 3
#define MODULE_LedModule_Version "0.13.0+ae43c83"
#define MODULE_LedModule_Version_Major 0
#define MODULE_LedModule_Version_Minor 13
#define MODULE_LedModule_Version_Revision 0
#define MODULE_LedModule_ETS 13
#define MODULE_SensorDevices_Version "4.1.1+369412c"
#define MODULE_SensorDevices_Version_Major 4
#define MODULE_SensorDevices_Version_Minor 1
#define MODULE_SensorDevices_Version_Revision 1
#define MODULE_SensorDevices_ETS 65
#define MODULE_SensorModule_Version "4.11.4+c5b3f06"
#define MODULE_SensorModule_Version_Major 4
#define MODULE_SensorModule_Version_Minor 11
#define MODULE_SensorModule_Version_Revision 4
#define MODULE_SensorModule_ETS 75
#define MODULE_SwitchActuator_Version "0.3.0+628478e"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 3
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 3
#define MODULE_VirtualButton_Version "0.6.0+9ea99b5"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 6
#define MODULE_VirtualButton_Version_Revision 0
#define MODULE_VirtualButton_ETS 6
