#pragma once

#define MAIN_Version "84aa6b0"
#define KNX_Version "2.3.1+49c1072"
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_Common_Version "1.7.2+e7a48eb"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 7
#define MODULE_Common_Version_Revision 2
#define MODULE_Common_ETS 23
#define MODULE_LogicModule_Version "4.2.0+3188092"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 2
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 66
#define MODULE_FunctionBlocks_Version "0.10.0+e8ec058"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 10
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 10
#define MODULE_BinaryInput_Version "0.2.1+7b628ef"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 2
#define MODULE_LedModule_Version "0.13.0-DEV+5f1fbdd"
#define MODULE_LedModule_Version_Major 0
#define MODULE_LedModule_Version_Minor 13
#define MODULE_LedModule_Version_Revision 0
#define MODULE_SensorDevices_Version "4.1.0+e0f860e"
#define MODULE_SensorDevices_Version_Major 4
#define MODULE_SensorDevices_Version_Minor 1
#define MODULE_SensorDevices_Version_Revision 0
#define MODULE_SensorDevices_ETS 65
#define MODULE_SensorModule_Version "4.10.0+c825b0c"
#define MODULE_SensorModule_Version_Major 4
#define MODULE_SensorModule_Version_Minor 10
#define MODULE_SensorModule_Version_Revision 0
#define MODULE_SensorModule_ETS 74
#define MODULE_SwitchActuator_Version "0.1.0+a03e80f"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
#define MODULE_VirtualButton_Version "0.5.2+034977c"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 5
#define MODULE_VirtualButton_Version_Revision 2
#define MODULE_VirtualButton_ETS 5
